# -*- coding: utf-8 -*-
"""bracia_BFF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KcswwRe7h_urdM017C8zIAls5gt7CJx
"""

#-*- coding: utf-8 -*-


import numpy as np
import urllib.request
from bs4 import BeautifulSoup
import re
import pandas as pd

pwd

# div class="ranking-lista"

URLS = ['https://www.tekstowo.pl/piosenki_artysty,bracia_figo_fagot.html', 
'https://www.tekstowo.pl/piosenki_artysty,bracia_figo_fagot,alfabetycznie,strona,2.html',
'https://www.tekstowo.pl/piosenki_artysty,bracia_figo_fagot,alfabetycznie,strona,3.html']

def dane(URL):
  page = urllib.request.urlopen(URL)
  soup = BeautifulSoup(page)
  temp = soup.body.findAll('div', attrs={'class' : 'box-przeboje'}) # zeby dowiedziec do jakiego elementu musimy sie odniesc, trzeba zajrzec do wnetrza strony
  return temp

dane(URLS[0]) #dostajemy wszystkie divy z class box-przeboje

URL = "https://www.tekstowo.pl/piosenki_artysty,bracia_figo_fagot.html"


page = urllib.request.urlopen(URL)

soup = BeautifulSoup(page)

lista = [content]
lista

songs_all_data = soup.body.findAll('div', attrs={'class' : 'ranking-lista'})

# temp[0].b
# temp[0].a
# temp[0].title
# temp[0].a.get('title')
# temp[0].a.get('href')

songs_all_data[0].a.get('title')

lista_piosenek = songs_all_data[0].findAll('a', attrs={'class' : 'title'})

kawalek = """a class="title" href="/piosenka,bracia_figo_fagot"""

type(kawalek)

type(lista_piosenek[0])

text = "bracia BFF         "

text

text.strip()

for linia in lista_piosenek:
  print(list(linia)[0].strip())

ULR2 = "file:///Users/macbook/Dropbox/Mój%20Mac%20(MacBook%20Pro%20(Macbook))/Downloads/DOMEK%20całoroczny%20Kontener%20mieszkalny%2035m2%20ARTHome%2010795259793%20-%20Allegro.pl.html"

page = urllib.request.urlopen(URL2)
soup = BeautifulSoup(page)

